# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/era5_sandbox',
                'doc_host': 'https://TinasheMTapera.github.io',
                'git_url': 'https://github.com/TinasheMTapera/era5_sandbox',
                'lib_path': 'era5_sandbox'},
  'syms': {'era5_sandbox.core': {'era5_sandbox.core.describe': ('core.html#describe', 'era5_sandbox/core.py')}}}
