"""Here we define the core functions that will be used in ERA5 repo."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notes/00_core.ipynb.

# %% auto 0
__all__ = ['describe']

# %% ../notes/00_core.ipynb 3
def describe():
    print("This package fetches ERA5 data.")
