defaults:
  - _self_
  - datapaths: datapaths
  - aggregation: aggregation
  - geographies: geographies

development_mode: false

CDS_API_KEY: 
  path: "$HOME/.cdsapirc"

GOOGLE_DRIVE_AUTH_JSON:
  path: "sandbox/harvard-csph-driveauth-f5f9a2682ecf.json"
  healthsheds_id: "healthsheds2022.zip"

mdg_shapefile: "https://data.humdata.org/dataset/26fa506b-0727-4d9d-a590-d2abee21ee22/resource/ed94d52e-349e-41be-80cb-62dc0435bd34/download/mdg_adm_bngrc_ocha_20181031_shp.zip"

dataset: "reanalysis-era5-single-levels"

query: 
  geography: ["madagascar", "nepal"]

  product_type: reanalysis
  variable: ["2m_dewpoint_temperature", "2m_temperature", "total_precipitation", "volumetric_soil_water_layer_1"]
  year: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
  month: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
  time: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

  area: [0, 360, -90, 90]
  data_format: netcdf
  download_format: unarchived

# logging config
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}