---
title: "Publish"
format: html
execute:
  engine: python
jupyter: python3
---

> This is the `publish` module for the ERA5 dataset pipeline. It defines a functions that make use of the `pyDataverse` library and API to publish our outputs to the Harvard Dataverse.

```{python}
#| default_export publish
```


```{python}
#| hide
from nbdev.showdoc import *
```

First, we'll test out the API by pinging the Harvard DataVerse


```{python}
#| export
#| 
from pyprojroot import here
import yaml
import json
```


```{python}
api_token_file = here() / "sandbox/dataverse_api_key.yml"
with open(api_token_file, "r") as f:
    config = yaml.load(f, Loader=yaml.BaseLoader)
```


Now, following the [docs]() for the dataverse tutorial, load a NativeAPI up:


```{python}
from pyDataverse.api import NativeApi
```


The NativeAPI is a catchall API object to be able to do general stuff:


```{python}
api = NativeApi(config['base_url'], config['api_token'])
resp=api.get_info_version()
```


```{python}
resp.text
```

Looks good! Now that we know that it works, we can think more
about how to publish data there.

## Harvard Dataverse

Let's create a dummy dataset with the components we're
planning to upload, and then upload and promptly delete it.

To do that, we must import the `models` module and create a Dataset object:

```{python}
from pyDataverse.models import Dataset
ds = Dataset()
```

This `ds` object is pretty straightforward since it doesn't contain anything yet:

```{python}
ds.get()
```

We can populate the object from the dummy data on the github repo:

```{python}
from pyDataverse.utils import read_file
from urllib.request import urlretrieve
import tempfile

url = "https://raw.githubusercontent.com/gdcc/pyDataverse/refs/heads/main/tests/data/user-guide/dataset.json"

with tempfile.NamedTemporaryFile(mode='w+') as tmp:
    urlretrieve(url, tmp.name)
    ds.from_json(read_file(tmp.name))
```

We have to validate the JSON correctly:

```{python}
ds.validate_json()
```

Modifying it is easy:

```{python}
ds.set({"title": "Youth from Austria 2005"})
ds.get()
```

Now, to create the dataset we use the API:

```{python}
#| eval: false
#| this is only run in interactive sessions for demo purposes
resp = api.create_dataset(":root", ds.json())
```

If you caught the `resp` object, it contains the PID for the newly created dataset.

However, if you didn't you can use the SearchAPI to find it:

```{python}
from pyDataverse.api import SearchApi

search_api = SearchApi(config['base_url'], config['api_token'])
resp = search_api.search("Youth from Austria", data_type="dataset")
```

```{python}
results = resp.json()['data']['items']
```

```{python}
result = [x for x in results if "Youth from Austria" in x['name']][0]
result
```

We can grab the PID of this entry:

```{python}
pid = result['global_id']
```

Now to look at the data we created using the NativeAPI again:

```{python}
uploaded_ds = api.get_dataset(pid)
uploaded_ds.json()['data']
```

Now, to delete this dataset:

```{python}
#| eval: false
#| only run in interactive testing
resp = api.delete_dataset(pid)
resp.json()
```

With that understanding, we can develop a quick module to do the following:

1. Make the dataset LEGO Compatible
2. Create metadata for the dataset entry
3. Bump the version
4. Upload and publish the data to dataverse

## LEGO Compatibility

Let's take an example file to use as a model for LEGO compatibility

```{python}
#| export
import geopandas as gpd
import pandas as pd
import re
import glob
```


```{python}
ex = gpd.read_parquet(here() / "data" / "testing" / "madagascar_environmental_exposure-era5_healthshed_2m_dewpoint_temperature_2009_6.parquet")
```

```{python}
ex.describe()
```

We know that the LEGO data model should look like this:

```
<main lab folder>/lego
├── <domain>
│   ├── <subdomain>__<data_source>
│   │   ├── <geo_resolution>__<time_resolution>
│   │   │   ├── <filename>_yyyy.parquet
```

So, for the above file, we'll end up with the LEGO path `data/environmental/exposures_era5/healthshed_monthly/dewpoint_2024.parquet`. In it, we should have the following columns:


```
healthshed_id  year month day stat_1 stat_2 ... stat_n   
```


This means we should read in all of the exposures for a single timepoint at once. 
I think the smart thing to do is use a glob string to gather all of the pertinent files.
This will be the first function we export to the library:

```{python}
#| export
# 

def gather_exposure_geodataframes(
    glob_string: str,   # string for the path to search for the pertinent files
    polygon_id: str,    # the string signifying the healthshed ID of the polygon
    exposure: str       # the exposure name
    )-> list:
    "Read in a list of geo dataframes from the same time frame and merge them"

    # first get the initial one so we have the polygon ID and geometry
    frames = glob.glob(str(glob_string))
    initial_gdf=gpd.read_parquet(frames[0])
    merged_df = []
  
    for f in frames:
        # read in as a regular dataframe by ignoring geometry
        df = gpd.read_parquet(f).drop(["geometry"], axis=1) 
        
        # get the year and month
        # Extract year and month
        match = re.search(r'_([a-z]+)_(\d{4})_(\d{1,2})\.parquet$', f)

        if match:
            #exposure = str(match.group(1))
            year = int(match.group(2))
            month = int(match.group(3))
            #print(f"Year: {year}, Month: {month}")
        else:
            #print("No match found.")
            pass
        df['exposure'] = exposure
        df['month'] = month
        df['year'] = year

        # Step 1: Melt all day columns (leave 'month' and 'year' as identifiers)
        df_long = df.melt(id_vars=[polygon_id, "exposure", "year", "month"], var_name="day_stat", value_name="value")

        # Step 2: Extract day and stat type from column names
        # Example column: "day_01_daily_mean"
        df_long[["day", "stat"]] = df_long["day_stat"].str.extract(r"day_(\d{2})_daily_(mean|max|min|total)")

        # Optional: convert 'day' and month to integer
        df_long["day"] = df_long["day"].astype(int)
        df_long["month"] = df_long["month"].astype(int)

        # Drop the original combined column
        df_long = df_long.drop(columns="day_stat")

        # Reorder columns
        df_long = df_long[[polygon_id, "exposure", "year", "month", "day", "stat", "value"]]

        df_long = df_long.sort_values(by=["year", "month", "day"])
        df_clean = df_long.pivot(index=["fs_uid", "exposure", "year", "month", "day"], columns="stat", values="value").reset_index()
        merged_df.append(df_clean)

    return [pd.concat(merged_df).reset_index(drop=True), initial_gdf[[polygon_id, "geometry"]]]
        
```

Now let's test this function out:

```{python}
frames = here() / "data" / "testing" / "*madagascar*"

merged = gather_exposure_geodataframes(frames, "fs_uid", "d2m")
merged[0].describe()
```

This returns one file with all of the geometries and one file
with the statistics and exposures.

Now, with this, we can move on.

## Dataset Metadata


On the dataverse, we can define a large metadata entry. Let's see
what are the required fields for entering data:

```{python}
resp = search_api.search("nsaph", data_type="dataverse")
nsaph_dv = resp.json()['data']['items'][0]['identifier']

nsaph_dv = api.get_dataverse(nsaph_dv)
```

We'll start with a basic metadata dictionary:


```{python}
ds = Dataset()
url = "https://raw.githubusercontent.com/gdcc/pyDataverse/refs/heads/main/tests/data/user-guide/dataset.json"

with tempfile.NamedTemporaryFile(mode='w+') as tmp:
    urlretrieve(url, tmp.name)
    ds.from_json(read_file(tmp.name))
```

Now we set the basic config:


```{python}
ds.set(
    {
        'title': "ERA5 Exposure Aggregations for MDG nd NPL",
        'author': [
            {
                'authorName': 'Tapera, Tinashe', 'authorAffiliation': 'Harvard University',
                'authorName': 'Golden, Christopher', 'authorAffiliation': 'Harvard University'
            }
        ],
        'datasetContact': [
            {
                'datasetContactEmail': 'ttapera@hsph.harvard.edu',
                'datasetContactName': 'Tapera, Tinashe'
            }
        ],
        'dsDescription': [
            {'dsDescriptionValue': 'This dataset contains daily aggregations of environmental exposures collected from the ERA5 Climate Data Store aggregated to geographic polygons in Madagascar and Nepal as part of the Climate-Smart Public Health project of the Golden Lab group at Harvard T.H. Chan School of Public Health. Exposures include 2-metre temperature, dewpoint temperature, total precipitation, and soil moisture. Aggregations include basic statistics per day within geospatial "healthsheds". The healthsheds\' geographies are provided directly by the respective governments.'}
        ],
        'subject': ['Medicine, Health and Life Sciences', 'Earth and Environmental Sciences'],

    }
)

# test 
assert ds.validate_json()
```

Now we create the dataset. We're doing this in the notebook, but the files will be
uploaded in the pipeline.

```{python}
# this fails because it needs a geospatial file
resp = api.create_dataset("nsaph", ds.json())
```

The response we get is an error:

```
'message': 'Validation Failed: Includes a Geospatial File is required.
```

So we need to figure out how to add that in:


```{python}
resp=api.get_metadatablocks()
resp.json()
```

Ok, so it looks like it's in the block called `customCAFEDataLocation`


```{python}
resp=api.get_metadatablock("customCAFEDataLocation")
resp.json()
```

We need to set the field `cafeIncludesGeospatialFile`:


```{python}
ds.set(
    {'cafeIncludesGeospatialFile': "Yes"}
)
assert ds.validate_json()
```


Now we create...

```{python}
# this similarly fails
resp = api.create_dataset("nsaph", ds.json())
```

It failed, so we need to add this:

```
'message': 'Validation Failed: Derived from Another Dataset is required.
```

Using the get_metadablocks() function, we found the block:

```{python}
resp=api.get_metadatablock('customCAFEDataSources')
resp.json()
```

```{python}
ds.set(
    {'cafeDerivedFromExistingDataset': "Yes"}
)
assert ds.validate_json()
```

```{python}
resp = api.create_dataset("nsaph", ds.json())
```

After these attempts, we just put it together on the website (though it may be
worth figuring out how this works).

The dataset is available via search:


```{python}
resp = search_api.search("ERA5", data_type="dataset")

results = resp.json()['data']['items']

result = [x for x in results if "ERA5" in x['name']][0]
era5_pid = result['global_id']
result

```

Now we can test uploading a file to this dataset:

```{python}
#| export

from pyDataverse.models import Datafile
import os
import pathlib
```

We'll upload directly from file. In the case of ERA5 vs. LEGO, we
store the file on disk as LEGO hierarchy, but to upload it to dataverse
using a flat filename (since creating subdatasets to represent directories might be 
a bit of a hassle)

```{python}
# assuming the file has a path on disk like:
f_out = "environmental/exposures_era5/healthshed_daily/dewpoint_2024.parquet"
os.makedirs(here() / "data" / "testing" / os.path.dirname(f_out), exist_ok=True)
aggregations, geo = merged
aggregations.to_parquet(here() / "data" / "testing" / f_out, index=False)
```

Now we upload

```{python}
datafile = Datafile()
datafile.set({
    # the id of the era5 dataset 
    "pid": era5_pid,
    # the path to the file on disk goes here
    "filename": str(here() / "data" / "testing" / f_out),
    # use the "label" to name the file
    "label": f_out.replace("/", "-")
})

```


```{python}
#| eval: false
resp = api.upload_datafile(era5_pid, str(here() / "data" / "testing" / f_out), datafile.json())
```

Pretty simple!

Now, we just need a main function to upload this data. The final upload is one file per
exposure per year, so these should be the variables we gather data for.

We should get some functionality to gather the groups of these files automatically, based on
the hydra config:

```{python}
#| export
from hydra import initialize, compose
from omegaconf import OmegaConf, DictConfig
from tqdm import tqdm
```

```{python}
target_dir = here() / "data" / "intermediate"

with initialize(version_base=None, config_path="../conf"):
    cfg = compose(config_name='config.yaml')

cfg.development_mode = False
#cfg.query['year'] = 2017
#cfg.query['month'] = 11
#cfg.query['geography'] = "nepal"
```

```{python}
@hydra.main(version_base=None, config_path="../../conf", config_name="config")
def main(cfg: DictConfig) -> None:
    # Parse command-line arguments
    input_file = str(snakemake.input[0])  # First input file
    output_file = str(snakemake.output[0])
    geography = str(snakemake.params.geography)
    aggregation_variable = str(snakemake.params.variable)

    variables_dict = {
        "2m_temperature": "t2m",
        "2m_dewpoint_temperature": "d2m",
        "volumetric_soil_water_layer_1": "swvl1",
        "total_precipitation": "tp"
    }

    cfg['query']['geography'] = geography
    
    print(cfg)
```