# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/era5_sandbox',
                'doc_host': 'https://TinasheMTapera.github.io',
                'git_url': 'https://github.com/TinasheMTapera/era5_sandbox',
                'lib_path': 'src/era5_sandbox'},
  'syms': { 'era5_sandbox.core': { 'era5_sandbox.core._expand_path': ('core.html#_expand_path', 'era5_sandbox/core.py'),
                                   'era5_sandbox.core.describe': ('core.html#describe', 'era5_sandbox/core.py'),
                                   'era5_sandbox.core.main': ('core.html#main', 'era5_sandbox/core.py'),
                                   'era5_sandbox.core.testAPI': ('core.html#testapi', 'era5_sandbox/core.py')},
            'era5_sandbox.download': { 'era5_sandbox.download._validate_query': ( 'download_raw_data.html#_validate_query',
                                                                                  'era5_sandbox/download.py'),
                                       'era5_sandbox.download.download': ('download_raw_data.html#download', 'era5_sandbox/download.py'),
                                       'era5_sandbox.download.fetch_MDG_GADM': ( 'download_raw_data.html#fetch_mdg_gadm',
                                                                                 'era5_sandbox/download.py'),
                                       'era5_sandbox.download.main': ('download_raw_data.html#main', 'era5_sandbox/download.py')}}}
