# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/20_pytask_config.qmd.

# %% auto 0
__all__ = ['SRC', 'BLD', 'demo_catalog', 'DEV_MODE', 'years', 'months', 'days', 'times', 'geographies', 'product_type',
           'variables', 'queries', 'products', 'data_catalog', 'inputs', 'outputs', 'variable_dict', 'agg_params',
           'mask', 'aggregate_jobs', 'Query']

# %% ../../notes/20_pytask_config.qmd 3
#| export: # imports

from pathlib import Path
from pyprojroot import here
from pytask import DataCatalog
from typing import NamedTuple


SRC = here() / "src" / "era5_sandbox"
BLD = here() / "bld"

demo_catalog = DataCatalog()

# %% ../../notes/20_pytask_config.qmd 5
#| export: # a dev flag for quick testing
DEV_MODE=True

# %% ../../notes/20_pytask_config.qmd 7
#| export: # download task parameters
years = [x for x in range(2009, 2025)]
months = [x for x in range(1, 13)]
days = [x for x in range(1, 32)]
times = [f"{x:02d}:00" for x in range(24)]
geographies = [
    {
        "name": "madagascar", 
        "shapefile": "https://data.humdata.org/dataset/26fa506b-0727-4d9d-a590-d2abee21ee22/resource/ed94d52e-349e-41be-80cb-62dc0435bd34/download/mdg_adm_bngrc_ocha_20181031_shp.zip"
    },
    {
        "name": "nepal", 
        "shapefile": "https://data.humdata.org/dataset/07db728a-4f0f-4e98-8eb0-8fa9df61f01c/resource/2eb4c47f-fd6e-425d-b623-d35be1a7640e/download/npl_adm_nd_20240314_ab_shp.zip"
    }
    ]
product_type = "reanalysis"
variables = ["2m_dewpoint_temperature", "2m_temperature", "total_precipitation", "volumetric_soil_water_layer_1"]

# %% ../../notes/20_pytask_config.qmd 9
#| export: # a class for the query parameters
class Query(NamedTuple):
    """A named tuple to hold the query parameters for the download."""
    year: str
    month: str
    day: list[str]
    time: list[str]
    geography: dict
    product_type: str
    variables: list[str]

    def name(self):
        """Return a unique name for the query based on year, month, and geography."""
        return f"{self.year}_{self.month}_{self.geography['name']}"
    def __str__(self):
        return f"Query(year={self.year}, month={self.month}, geography={self.geography['name']})"

queries = []

for year in years:
    for month in months:
        for geography in geographies:
            queries.append(Query(str(year), str(month), [str(x) for x in days], times, geography, product_type, variables))

# %% ../../notes/20_pytask_config.qmd 12
#| export: # set up catalog

products = ["mydata", 'mydata2', "download", "aggregate", "viz", "publish"]

data_catalog = {

    product: DataCatalog(name=f"{product}")
    for product in products
}
data_catalog['download'].add("queries", queries)

# %% ../../notes/20_pytask_config.qmd 14
#| export: # aggregate task parameters

inputs = [x.name() for x in data_catalog['download']['queries'].load()]
outputs = [f"{i}_agg" for i in inputs]

variable_dict = {
    "2m_dewpoint_temperature": "d2m",
    "2m_temperature": "t2m",
    "total_precipitation": "tp",
    "volumetric_soil_water_layer_1": "swvl1"
}

# list of params that get fed into the task functions
agg_params = {
    "time": ["day", "night"],
    "solar_classification": ["before"],
    "variables": variables,
    "variables_short": [variable_dict[x] for x in variables],
    "aggregation_name": ["mean", "sum", "max", "min"]
}

from itertools import product
import pandas as pd

# expand all the params
agg_params = pd.DataFrame(list(product(*agg_params.values())), columns=agg_params.keys())

# %% ../../notes/20_pytask_config.qmd 18
#| export: # quick filter to keep only matching rows

agg_params = agg_params[agg_params.apply(lambda x: variable_dict[x['variables']] == x['variables_short'], axis=1)]

# %% ../../notes/20_pytask_config.qmd 21
#| export: # remove rows where tp aggregation is not sum
mask = (agg_params['variables_short'] == "tp") & (agg_params['aggregation_name'] != "sum")
agg_params = agg_params[~mask]

# remove rows where non-tp aggregation is sum
mask = (agg_params['variables_short'] != "tp") & (agg_params['aggregation_name'] == "sum")
agg_params = agg_params[~mask]

# %% ../../notes/20_pytask_config.qmd 24
#| export: # set up inputs and parameters
inputs = pd.DataFrame({"input": inputs})
aggregate_jobs = inputs.merge(agg_params, how="cross")

# %% ../../notes/20_pytask_config.qmd 28
#| export: # add a few more columns
aggregate_jobs['local_tz'] = aggregate_jobs['input'].apply(
    lambda x: "Asia/Kathmandu" if "nepal" in x else "Indian/Antananarivo"
)
aggregate_jobs['shapefile'] = aggregate_jobs['input'].apply(
    lambda x: "Nepal_Healthsheds2024.zip" if "nepal" in x else "healthsheds2022.zip"
)

aggregate_jobs['hshd_unique_id'] = aggregate_jobs['input'].apply(
    lambda x: "fid" if "nepal" in x else "fs_uid"
)

aggregate_jobs['climate_handler_var'] = aggregate_jobs['variables_short'].apply(
    lambda x: "accum" if x == "tp" else "instant"
)

# %% ../../notes/20_pytask_config.qmd 31
#| export: # update catalog
data_catalog['aggregate'].add("jobs", aggregate_jobs)
