# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/20_pytask_config.qmd.

# %% auto 0
__all__ = ['SRC', 'BLD', 'demo_catalog', 'DEV_MODE', 'years', 'months', 'days', 'times', 'geographies', 'product_type',
           'variables', 'queries', 'products', 'data_catalog', 'Query']

# %% ../../notes/20_pytask_config.qmd 3
from pathlib import Path
from pyprojroot import here
from pytask import DataCatalog
from typing import NamedTuple


SRC = here() / "src" / "era5_sandbox"
BLD = here() / "bld"

demo_catalog = DataCatalog()

# %% ../../notes/20_pytask_config.qmd 5
DEV_MODE=False

# %% ../../notes/20_pytask_config.qmd 7
# download task parameters
years = [x for x in range(2009, 2025)]
months = [x for x in range(1, 13)]
days = [x for x in range(1, 32)]
times = [f"{x:02d}:00" for x in range(24)]
geographies = [
    {
        "name": "madagascar", 
        "shapefile": "https://data.humdata.org/dataset/26fa506b-0727-4d9d-a590-d2abee21ee22/resource/ed94d52e-349e-41be-80cb-62dc0435bd34/download/mdg_adm_bngrc_ocha_20181031_shp.zip"
    },
    {
        "name": "nepal", 
        "shapefile": "https://data.humdata.org/dataset/07db728a-4f0f-4e98-8eb0-8fa9df61f01c/resource/2eb4c47f-fd6e-425d-b623-d35be1a7640e/download/npl_adm_nd_20240314_ab_shp.zip"
    }
    ]
product_type = "reanalysis"
variables = ["2m_dewpoint_temperature", "2m_temperature", "total_precipitation", "volumetric_soil_water_layer_1"]

# %% ../../notes/20_pytask_config.qmd 9
class Query(NamedTuple):
    """A named tuple to hold the query parameters for the download."""
    year: str
    month: str
    day: list[str]
    time: list[str]
    geography: dict
    product_type: str
    variables: list[str]

    def name(self):
        """Return a unique name for the query based on year, month, and geography."""
        return f"{self.year}_{self.month}_{self.geography['name']}"
    def __str__(self):
        return f"Query(year={self.year}, month={self.month}, geography={self.geography['name']})"

queries = []

for year in years:
    for month in months:
        for geography in geographies:
            queries.append(Query(str(year), str(month), [str(x) for x in days], times, geography, product_type, variables))

# %% ../../notes/20_pytask_config.qmd 12
products = ["mydata", 'mydata2', "download", "aggregate", "viz", "publish"]

data_catalog = {

    product: DataCatalog(name=f"{product}")
    for product in products
}
data_catalog['download'].add("queries", queries)
