# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/20_pytask_config.ipynb.

# %% auto 0
__all__ = ['SRC', 'BLD', 'demo_catalog', 'DEV_MODE', 'stages', 'buckets', 'data_catalog', 'years', 'months', 'geographies',
           'days', 'times', 'variables', 'product_type', 'shapefiles', 'rows', 'query_df', 'inputs', 'outputs',
           'variable_dict', 'agg_params', 'mask', 'aggregate_jobs']

# %% ../../notes/20_pytask_config.ipynb 3
#| exports: #

import pandas as pd

from pathlib import Path
from pyprojroot import here
from pytask import DataCatalog


SRC = here() / "src" / "era5_sandbox"
BLD = here() / "bld"

demo_catalog = DataCatalog()

# %% ../../notes/20_pytask_config.ipynb 5
#| exports: #
DEV_MODE=True

# %% ../../notes/20_pytask_config.ipynb 7
#| exports: #

stages = ["mydata", 'mydata2', # from the demo, ignore
    "download", # download task
    "aggregate", # aggregation task
    "publish", # publishing task
    "viz"] # visualization task

buckets = [
    "inputs", # any specific inputs, eg for carrying over between tasks
    "outputs", # specific output task returns
    "jobs", # job parameters as a dataframe
    "params" # any lingering hardcoded parameters
    ]

data_catalog = {

    stage: {bucket: DataCatalog(name=f"{stage}_{bucket}") for bucket in buckets}
    for stage in stages
}

# %% ../../notes/20_pytask_config.ipynb 9
#| exports: # a dataframe for the query parameters, with nested entries for days, times, and variables
# Dimensions
years = [str(x) for x in range(2009, 2025)]  # 16 years
months = [str(x).zfill(2) for x in range(1, 13)]      # 12 months
geographies = ["madagascar", "nepal"]  # 2 geographies

# nested values; we want ALL days, times, and variables for each job
days = [str(x).zfill(2) for x in range(1, 32)]
times = [f"{x:02d}:00" for x in range(24)]
variables = ["2m_dewpoint_temperature", "2m_temperature", "total_precipitation", "volumetric_soil_water_layer_1"]

product_type = "reanalysis"

# Map shapefiles to geography
shapefiles = {
    "madagascar": "https://data.humdata.org/dataset/26fa506b-0727-4d9d-a590-d2abee21ee22/resource/ed94d52e-349e-41be-80cb-62dc0435bd34/download/mdg_adm_bngrc_ocha_20181031_shp.zip",
    "nepal": "https://data.humdata.org/dataset/07db728a-4f0f-4e98-8eb0-8fa9df61f01c/resource/2eb4c47f-fd6e-425d-b623-d35be1a7640e/download/npl_adm_nd_20240314_ab_shp.zip"
}

# Build row-wise combinations of (year, month, geography)
rows = []
for year in years:
    for month in months:
        for geo in geographies:
            rows.append({
                "year": year,
                "month": month,
                "geography": geo,
                "shapefile": shapefiles[geo],
                "product_type": product_type,
                "day": days,
                "time": times,
                "variables": variables,
                "output": f"{year}_{month}_{geo}"
            })

# Create dataframe
query_df = pd.DataFrame(rows)

# %% ../../notes/20_pytask_config.ipynb 13
#| export: # set up catalog

data_catalog['download']['jobs'].add("queries_df", query_df)

# %% ../../notes/20_pytask_config.ipynb 17
#| exports: # aggregate task parameters

inputs = query_df["output"].tolist()
outputs = [f"{i}_agg" for i in inputs]

variable_dict = {
    "2m_dewpoint_temperature": "d2m",
    "2m_temperature": "t2m",
    "total_precipitation": "tp",
    "volumetric_soil_water_layer_1": "swvl1"
}

# list of params that get fed into the task functions
agg_params = {
    "time": ["day", "night"],
    "solar_classification": ["before"],
    "variables": variables,
    "variables_short": [variable_dict[x] for x in variables],
    "aggregation_name": ["mean", "sum", "max", "min"]
}

from itertools import product
import pandas as pd

# expand all the params
agg_params = pd.DataFrame(list(product(*agg_params.values())), columns=agg_params.keys())

# %% ../../notes/20_pytask_config.ipynb 21
#| exports: # quick filter to keep only matching rows

agg_params = agg_params[agg_params.apply(lambda x: variable_dict[x['variables']] == x['variables_short'], axis=1)]

# %% ../../notes/20_pytask_config.ipynb 24
#| exports: # remove rows where tp aggregation is not sum
mask = (agg_params['variables_short'] == "tp") & (agg_params['aggregation_name'] != "sum")
agg_params = agg_params[~mask]

# remove rows where non-tp aggregation is sum
mask = (agg_params['variables_short'] != "tp") & (agg_params['aggregation_name'] == "sum")
agg_params = agg_params[~mask]

# %% ../../notes/20_pytask_config.ipynb 27
#| exports: # set up inputs and parameters
inputs = pd.DataFrame({"input": inputs})
aggregate_jobs = inputs.merge(agg_params, how="cross")

# %% ../../notes/20_pytask_config.ipynb 31
#| exports: # add a few more columns
aggregate_jobs['local_tz'] = aggregate_jobs['input'].apply(
    lambda x: "Asia/Kathmandu" if "nepal" in x else "Indian/Antananarivo"
)
aggregate_jobs['shapefile'] = aggregate_jobs['input'].apply(
    lambda x: "Nepal_Healthsheds2024.zip" if "nepal" in x else "healthsheds2022.zip"
)

aggregate_jobs['hshd_unique_id'] = aggregate_jobs['input'].apply(
    lambda x: "fid" if "nepal" in x else "fs_uid"
)

aggregate_jobs['climate_handler_var'] = aggregate_jobs['variables_short'].apply(
    lambda x: "accum" if x == "tp" else "instant"
)

# %% ../../notes/20_pytask_config.ipynb 34
#| exports: # update catalog
data_catalog['aggregate']['jobs'].add("jobs_df", aggregate_jobs)
