# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/03_publish.ipynb.

# %% auto 0
__all__ = ['gather_exposure_geodataframes', 'main']

# %% ../../notes/03_publish.ipynb 4
#| exports: #
import hydra
import yaml
import json
from tqdm import tqdm
from pyprojroot import here

# %% ../../notes/03_publish.ipynb 7
#| exports: #
from pyDataverse.api import NativeApi

# %% ../../notes/03_publish.ipynb 26
#| exports: #
from pyDataverse.api import SearchApi

# %% ../../notes/03_publish.ipynb 33
#| exports: #
import geopandas as gpd
import pandas as pd
import re
import glob

# %% ../../notes/03_publish.ipynb 36
#| exports: # 

def gather_exposure_geodataframes(
    glob_string: str,   # string for the path to search for the pertinent files
    polygon_id: str,    # the string signifying the healthshed ID of the polygon
    exposure: str       # the exposure name
    )-> list:
    "Read in a list of geo dataframes from the same time frame and merge them"

    # first get the initial one so we have the polygon ID and geometry
    frames = glob.glob(str(glob_string))
    initial_gdf=gpd.read_parquet(frames[0])
    merged_df = []
  
    for f in tqdm(frames, desc="Processing files"):
        # read in as a regular dataframe by ignoring geometry
        df = gpd.read_parquet(f).drop(["geometry"], axis=1) 
        
        # get the year and month
        # Extract year and month
        search_str = rf'_{exposure}_(\d{{4}})_(\d{{1,2}})\.parquet$'
        match = re.search(search_str, f)

        if match:
            year = int(match.group(1))
            month = int(match.group(2))
            #print(f"Year: {year}, Month: {month}")
        else:
            raise ValueError(f"Could not extract year and month from filename: {search_str} {f}")
            
        df['exposure'] = exposure
        df['month'] = month
        df['year'] = year

        # Step 1: Melt all day columns (leave 'month' and 'year' as identifiers)
        df_long = df.melt(id_vars=[polygon_id, "exposure", "year", "month"], var_name="day_stat", value_name="value")

        # Step 2: Extract day and stat type from column names
        # Example column: "day_01_daily_mean"
        df_long[["day", "stat"]] = df_long["day_stat"].str.extract(r"day_(\d{2})_daily_(mean|max|min|total)")

        # Optional: convert 'day' and month to integer
        df_long["day"] = df_long["day"].astype(int)
        df_long["month"] = df_long["month"].astype(int)

        # Drop the original combined column
        df_long = df_long.drop(columns="day_stat")

        # Reorder columns
        df_long = df_long[[polygon_id, "exposure", "year", "month", "day", "stat", "value"]]

        df_long = df_long.sort_values(by=["year", "month", "day"])
        df_clean = df_long.pivot(index=[polygon_id, "exposure", "year", "month", "day"], columns="stat", values="value").reset_index()
        merged_df.append(df_clean)

    return [pd.concat(merged_df).reset_index(drop=True), initial_gdf[[polygon_id, "geometry"]]]

# %% ../../notes/03_publish.ipynb 40
#| exports: #

from pyDataverse.models import Datafile
import os
import pathlib

# %% ../../notes/03_publish.ipynb 45
#| exports: #
from hydra import initialize, compose
from omegaconf import OmegaConf, DictConfig
from tqdm import tqdm

# %% ../../notes/03_publish.ipynb 47
#| exports: #

@hydra.main(version_base=None, config_path="../../conf", config_name="config")
def main(cfg: DictConfig) -> None:

    variables_dict = {
        "2m_temperature": "t2m",
        "2m_dewpoint_temperature": "d2m",
        "volumetric_soil_water_layer_1": "swvl1",
        "total_precipitation": "tp"
    }

    print(OmegaConf.to_yaml(cfg))

    #prep dataverse
    api_token_file = here() / "sandbox/dataverse_api_key.yml"
    with open(api_token_file, "r") as f:
        apiconfig = yaml.load(f, Loader=yaml.BaseLoader)
    api = NativeApi(apiconfig['base_url'], apiconfig['api_token'])
    search_api = SearchApi(apiconfig['base_url'], apiconfig['api_token'])
    resp = search_api.search("ERA5", data_type="dataset")

    results = resp.json()['data']['items']

    result = [x for x in results if "ERA5" in x['name']][0]
    era5_pid = result['global_id']

    for geography in cfg.geographies:
        for year in cfg.query['year']:
            for variable, v in variables_dict.items():
                
                print(f"Processing {geography} for {variable} in {year}")
                glob_string = here() / "data" / "intermediate" / f"*{geography}*{variable}*{year}*"
                print(f"Glob: {glob_string}")
                polygon_id = cfg.geographies[geography]['unique_id']
                print(f"polygon_id: {polygon_id}")
                merged = gather_exposure_geodataframes(glob_string, polygon_id, variable)
                print(merged[0].head())
                print(merged[1].head())

                output_dir = here() / "data" / "output" 
                
                f_out = f"environmental/exposures_era5/healthshed_daily/{geography}_{v}_{year}.parquet"
                os.makedirs(output_dir / os.path.dirname(f_out), exist_ok=True)
                output_path = output_dir / f_out

                print(f"Writing to {output_path}")
                merged[0].to_parquet(output_path, index=False)
                

                print(f"Uploading {f_out.replace('/', '-')} to Dataverse...")
                # upload to dataverse
                datafile = Datafile()
                datafile.set({
                    "pid": era5_pid,
                    "filename": str(output_path),
                    "label": f_out.replace("/", "-")
                })

                resp = api.upload_datafile(era5_pid, output_path, datafile.json())
                assert resp.json()['status'] == "OK", f"Failed to upload datafile: {resp.text}"
        
        # also save the geometry for the region 
        merged[1].to_parquet(output_path.parent / f"{geography}_geometry.parquet", index=False)

        # and upload it to dataverse
        datafile = Datafile()
        datafile.set({
            "pid": era5_pid,
            "filename": str(output_path.parent / f"{geography}_geometry.parquet"),
            "label": f"{geography}_geometry.parquet"
        })

        resp = api.upload_datafile(era5_pid, output_path.parent / f"{geography}_geometry.parquet", datafile.json())
        assert resp.json()['status'] == "OK", f"Failed to upload geometry datafile: {resp.text}"

    print("All files processed and uploaded successfully.")

# %% ../../notes/03_publish.ipynb 48
#| export: #| eval: false
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if __name__ == "__main__" and not IN_NOTEBOOK:
    main()
