# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/20_pytask_logger.qmd.

# %% auto 0
__all__ = ['LOG_DIR', 'setup_logger']

# %% ../../notes/20_pytask_logger.qmd 3
import logging
from pathlib import Path
from pyprojroot import here

LOG_DIR = here("logs")
LOG_DIR.mkdir(exist_ok=True)

# %% ../../notes/20_pytask_logger.qmd 4
def setup_logger(name: str, log_file: Path, level=logging.INFO) -> logging.Logger:
    formatter = logging.Formatter('%(asctime)s — %(name)s — %(levelname)s — %(message)s')

    handler = logging.FileHandler(log_file, mode='a')
    handler.setFormatter(formatter)

    logger = logging.getLogger(name)
    logger.setLevel(level)
    logger.addHandler(handler)
    logger.propagate = False

    return logger
