# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/22_pytask_aggregate.qmd.

# %% auto 0
__all__ = ['compute_diurnal_class', 'resample_netcdf_diurnal', 'netcdf_to_tiff_diurnal']

# %% ../../notes/22_pytask_aggregate.qmd 3
import tempfile
import rasterio
import xarray as xr
from pyprojroot import here
from typing import Literal
from rasterstats.io import Raster
from .config import BLD, data_catalog
from .core import ClimateDataFileHandler

from .core import GoogleDriver, _get_callable, describe, ClimateDataFileHandler, kelvin_to_celsius

from .aggregate import polygon_to_raster_cells, aggregate_to_healthsheds, RasterFile

# %% ../../notes/22_pytask_aggregate.qmd 7
from astral import Observer, sun
import pandas as pd
import numpy as np
from tqdm import tqdm
import random

# %% ../../notes/22_pytask_aggregate.qmd 13
def compute_diurnal_class(
        ds: xr.Dataset
    )-> list:
    """
    Compute the diurnal value for each data point in the dataset.
    This function iterates over each data point in the dataset,
    calculates the sunrise and sunset times for the given time, latitude and longitude,
    and returns whether or not that data point is daytime or nighttime.
    """
    diurnal_class = []
    
    for i in tqdm(range(len(ds['valid_time'])), desc="Computing diurnal class"):
        time = ds['valid_time'].values[i]
        dt = pd.to_datetime(time, utc=True)
        observer = Observer(latitude=lat, longitude=long, elevation=0)
        sun_info = sun.sun(observer, date=dt)

        if dt < sun_info['sunrise']:
            diurnal_class.append("pre_dawn")
        elif dt >= sun_info['sunrise'] and dt < sun_info['sunset']:
            diurnal_class.append("day")
        else:
            diurnal_class.append("post_dusk")
    
    return diurnal_class

# %% ../../notes/22_pytask_aggregate.qmd 24
def resample_netcdf_diurnal(
        fpath: str, # Path to the netCDF file.
        diurnal_col: str = "diurnal_class", # Name of the column for diurnal classification.
        agg_func: callable = np.mean, # Aggregation function (e.g., np.mean, np.sum).
        time_dim: str = "valid_time", # Name of the time dimension in the dataset.
        chunks: dict | None = None # keywords for python's xarray module, e.g chunking
    ) -> xr.Dataset:   
    """
    Resample a netCDF file to a specified frequency and aggregation method.
    
    Args:
        fpath (str): Path to the netCDF file.
        diurnal_col (str): Name of the column for diurnal classification.
        agg_func (callable): Aggregation function (e.g., np.mean, np.sum).
    
    Returns:
        xarray.Dataset: Resampled dataset.
    """
    if chunks is None:
        with ClimateDataFileHandler(fpath) as handler:
            fpath = handler.get_dataset("instant")
            ds = xr.open_dataset(fpath)
    else:
        with ClimateDataFileHandler(fpath) as handler:
            fpath = handler.get_dataset("instant")
            ds = xr.open_dataset(fpath, chunks=chunks)

    diurnal_vals = compute_diurnal_class(ds)
    ds = ds.assign_coords(**{diurnal_col: ("valid_time", diurnal_vals)})

    if callable(agg_func):
        # Use xarray's reduce method with the callable
        ds.coords["date"] = ds[time_dim].dt.floor("D")
        return ds.groupby(["date", diurnal_col]).reduce(agg_func, dim=time_dim)
    else:
        raise TypeError("agg_func must be a callable function like np.mean, np.max, etc.")

# %% ../../notes/22_pytask_aggregate.qmd 29
def netcdf_to_tiff_diurnal(
    ds: xr.Dataset, # The aggregated xarray dataset to convert.    
    band: int,      # The day to rasterise; 1 indexed just like human english
    variable: str, # The variable name to convert.
    diurnal_class: Literal["pre_dawn", "day", "post_dusk"], # special parameter for the diurnal pipeline; writing the predawn, day, or post_dusk data  
    crs: str = "EPSG:4326" # Coordinate reference system (default is WGS84). 
    ):

    """
    Convert a netCDF file to a GeoTIFF file.
    """

    with tempfile.TemporaryDirectory() as tmpdirname:

        # Select the variable and time index
        variable = ds[variable].sel(diurnal_class=diurnal_class)
        ds_ = variable.rio.set_spatial_dims(x_dim="longitude", y_dim="latitude").transpose('date', 'latitude', 'longitude')
        ds_ = ds_.rio.write_crs(crs)
        # Save as GeoTIFF
        ds_.rio.to_raster(f"{tmpdirname}/output.tif")
        # Load the raster file
        raster_file = RasterFile(path=f"{tmpdirname}/output.tif", band=band).load()

    return raster_file
