# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/21_pytask_download.ipynb.

# %% auto 0
__all__ = ['queries']

# %% ../../notes/21_pytask_download.ipynb 4
#| export: # necessary imports
import cdsapi
import pytask
import os
from pytask import task, Product
from pathlib import Path
from typing import Annotated
from pandas import Series

from .config import data_catalog
from .config import BLD
from .config import DEV_MODE
from .pytask_logger import setup_logger
from .download import fetch_GADM, create_bounding_box

# %% ../../notes/21_pytask_download.ipynb 12
#| export: # define the download task

queries = data_catalog['download']['jobs']['queries_df'].load()

for i, job in queries.iterrows():

    @task(id=job['output'], name=f"Download {job['output']}")
    def task_download_raw_data(
        _query: Series = job   # The query object from the data catalog
    )-> Annotated[Path, data_catalog['download']['outputs'][job['output']]]:
        
        logger = setup_logger(_query['output'])
        output_path = BLD / f"{_query['output']}.nc"
        logger.info(f"Starting download for {_query['output']} to {output_path}")

        # check if string file path exists
        if os.path.exists(output_path):
            logger.info(f"File {output_path} already exists. Skipping download.")
            return output_path

        client = cdsapi.Client()
        bounding_box = create_bounding_box(_query['shapefile'])
    
        request = {
                "product_type": _query['product_type'],
                "variable": _query['variables'], 
                "year": _query['year'],
                "month": _query['month'],
                "day": _query['day'],
                "time": _query['time'],
                "data_format": "netcdf",
                "download_format": "unarchived",
                "area": bounding_box
            }
                
        client.retrieve("reanalysis-era5-land", request).download(output_path)
        logger.info(f"Downloaded data for {_query['output']} to {output_path}")

        return output_path
