# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/22_pytask_aggregate.ipynb.

# %% auto 0
__all__ = ['job_rows', 'aggregation_funcs', 'compute_diurnal_class_bins', 'compute_solar_day_night_class_bins']

# %% ../../notes/22_pytask_aggregate.ipynb 3
#| export: #

import os
import tempfile
import rasterio
import yaml
import xarray as xr
from pyprojroot import here
from typing import Literal
from pytask import task, Product
from pathlib import Path
from typing import Annotated
from rasterstats.io import Raster

from .config import BLD, data_catalog
from .pytask_logger import setup_logger

from .core import GoogleDriver, _get_callable, describe, ClimateDataFileHandler, kelvin_to_celsius

from .aggregate import polygon_to_raster_cells, aggregate_to_healthsheds, RasterFile, netcdf_to_tiff

# %% ../../notes/22_pytask_aggregate.ipynb 7
#| exports: #
from astral import Observer, sun
import pandas as pd
import numpy as np
from tqdm import tqdm
import random
import datetime
from pytz import UTC

# %% ../../notes/22_pytask_aggregate.ipynb 17
#| export: # define the basic diurnal classification function

def compute_diurnal_class_bins(
        ds: xr.Dataset
    )-> np.ndarray:
    """
    Compute the diurnal value for each data point in the dataset.
    This function iterates over each data point in the dataset,
    calculates the sunrise and sunset times for the given time, latitude and longitude,
    and returns whether or not that data point is before dawn, during the day, or after dusk.
    """

    times = ds['valid_time'].values
    lats = ds.coords['latitude'].values
    lons = ds.coords['longitude'].values

    result = np.full((len(times), len(lats), len(lons)), "", dtype=object)

    for i, dt in enumerate(tqdm(times, desc="Classifying data points by sun position")):
        # use the time
        dt = pd.to_datetime(dt, utc=True)

        for j, lat in enumerate(lats):

            for k, lon in enumerate(lons):
                
                # set the geographical position
                observer = Observer(latitude=lat, longitude=lon, elevation=0)
                
                # where/when is the sun at this time for this position
                sun_info = sun.sun(observer, date=dt)
                
                if dt < sun_info['sunrise']:
                    result[i, j, k] = "pre_dawn"
                elif dt >= sun_info['sunrise'] and dt < sun_info['sunset']:
                    result[i, j, k] = "day"
                else:
                    result[i, j, k] = "post_dusk"

    return result

# %% ../../notes/22_pytask_aggregate.ipynb 22
#| exports: # 

def compute_solar_day_night_class_bins(
        ds: xr.Dataset,
        night_direction: Literal["before", "after"],
    )-> list:
    """
    Compute the diurnal value for each data point in the dataset.
    This function iterates over each data point in the dataset,
    calculates the sunrise and sunset times for the given time, latitude and longitude,
    and returns whether or not that data point is daytime or nighttime.
    The definition of "nighttime" can be set to be all the darkness before the sun
    came up (before), or all the darkness after it went down (after).
    """

    times = ds['valid_time'].values
    lats = ds.coords['latitude'].values
    lons = ds.coords['longitude'].values

    result = np.full((len(times), len(lats), len(lons)), "", dtype=object)
    datetimes = np.full((len(times), len(lats), len(lons)), "", dtype=object)

    for i, dt in enumerate(tqdm(times, desc="Classifying data points by sun position")):
        # use the time
        dt = pd.to_datetime(dt, utc=True)

        for j, lat in enumerate(lats):

            for k, lon in enumerate(lons):
                
                # set the geographical position
                observer = Observer(latitude=lat, longitude=lon, elevation=0)
                if night_direction == "before":
                    # Night is from previous sunset to today's sunrise
                    sun_today = sun.sun(observer, date=dt.date())
                    sun_prev = sun.sun(observer, date=(dt - pd.Timedelta(days=1)).date())
                    night_start = sun_prev["sunset"].astimezone(pd.Timestamp.utcnow().tz)
                    night_end = sun_today["sunrise"].astimezone(pd.Timestamp.utcnow().tz)
                    
                    # the reading is from yesterday's nighttime
                    if night_start <= dt < night_end:
                        result[i, j, k] = "night"
                        # the date counts as today
                        datetimes[i, j, k] = dt.date()

                    # the reading is from daytime
                    elif sun_today["sunrise"] <= dt < sun_today["sunset"]:
                        result[i, j, k] = "day"
                        # the date counts as today
                        datetimes[i, j, k] = dt.date()
                    
                    # the reading is from today's nighttime, but counts as tomorrow's night
                    else:
                        result[i, j, k] = "night"
                        # the date is tomorrow
                        datetimes[i, j, k] = (dt + pd.Timedelta(days=1)).date()

                elif night_direction == "after":
                    # Night is from today's sunset to next sunrise
                    sun_today = sun.sun(observer, date=dt.date())
                    sun_next = sun.sun(observer, date=(dt + pd.Timedelta(days=1)).date())
                    night_start = sun_today["sunset"].astimezone(pd.Timestamp.utcnow().tz)
                    night_end = sun_next["sunrise"].astimezone(pd.Timestamp.utcnow().tz)

                    # the reading is from daytime
                    if sun_today["sunrise"] <= dt < sun_today["sunset"]:
                        result[i, j, k] = "day"
                        # the date counts as today
                        datetimes[i, j, k] = dt.date()
                    # the reading is from tonight
                    elif night_start <= dt < night_end:
                        result[i, j, k] = "night"
                        # the date counts as today
                        datetimes[i, j, k] = dt.date()

                    # the reading is from yesterday night
                    else:
                        # the date counts as yesterday
                        result[i, j, k] = "day"
                        datetimes[i, j, k] = (dt - pd.Timedelta(days=1)).date()
                else:
                    raise ValueError(f"Invalid night_direction: {night_direction}")

    return result, datetimes

# %% ../../notes/22_pytask_aggregate.ipynb 49
#| exports: #

job_rows = data_catalog['aggregate']['jobs']['jobs_df'].load()

aggregation_funcs = {
    "mean": np.nanmean,
    "sum": np.nansum,
    "max": np.nanmax,
    "min": np.nanmin
}

for i, job in job_rows.iterrows():
    #print(f"Job {i+1}: variable={job['variables']}, time={job['time']}, aggregation={job['aggregation_name']}")

    # parse the row into function parameters
    input_file = data_catalog['download']['outputs'][job['input']]
    solar_classification = job['solar_classification']
    variable = job['variables_short']
    time = job['time']
    aggregation_func = aggregation_funcs[job['aggregation_name']]
    aggregation_name = job['aggregation_name']

    climate_handler_var = job['climate_handler_var']
    local_tz = job['local_tz']

    shapefile = job['shapefile']
    hshd_unique_id = job['hshd_unique_id']

    output_file = job['input'] + "_" + job['time'] + "_" + job['variables_short'] + "_" + job['aggregation_name'] + ".parquet"

    @task(id=output_file, name=f"Aggregate {output_file}", after="task_download_raw_data")
    def task_aggregate_data_diurnal(
            input_file: Path = data_catalog['download']['outputs'][job['input']], # input data Path from the download task
            aggregation_func: callable = aggregation_func, # the aggregation function
            aggregation_name: str = aggregation_name, # the name of the aggregation function
            time: Literal["day", "night"] = time, # whether to aggregate by day or night
            night_direction: Literal["before", "after"] = solar_classification, # how to define night
            variable: str = variable, # the variable to aggregate,
            climate_handler_var: Literal["instant", "accum"] = climate_handler_var, # whether the variable is instant or accum,
            local_tz: str = local_tz, # the local timezone for resampling
            shapefile: str = shapefile, # the shapefile for the healthsheds,
            hshd_unique_id: str = hshd_unique_id, # the unique id column in the shapefile,
            output_file: str = output_file # the output file name
        ) -> Annotated[Path, data_catalog['aggregate']['outputs'][output_file]]:
        """
        Task to aggregate data from a CDSAPI Query to the healthshed
        level. Returns path to parquet file with aggregated data.
        """

        logger = setup_logger(output_file)

        logger.info(f"Aggregating: {output_file}")

        # check if the string path exists
        # if os.path.exists(output_file):
        #     logger.info(f"File {output_file} already exists. Skipping aggregation.")
        #     return output_file

        # get input data
        logger.info("Reading input data...")
        with ClimateDataFileHandler(input_file) as handler:
            ds = xr.open_dataset(handler.get_dataset('instant'))

        #get the healthshed shapefile
        logger.info(f"Reading healthshed shapefile from yaml {here()}...")
        with open(here() / "conf" / "config.yaml") as f:
            healthshed_config = yaml.safe_load(f)

            key_path = here() / healthshed_config['GOOGLE_DRIVE_AUTH_JSON']['path']

            driver = GoogleDriver(json_key_path=key_path)
            drive = driver.get_drive()
            healthsheds = driver.read_healthsheds(shapefile)

        # compute the diurnal classification bins
        logger.info("Computing diurnal classification bins...")
        class_bins, class_dts = compute_solar_day_night_class_bins(ds, night_direction)

        ds_masked = ds.copy()

        # assign classifications
        logger.info("Assigning classification bins to dataset...")
        ds['solar_class'] = (('valid_time', 'latitude', 'longitude'), class_bins)
        ds["solar_date"] = (("valid_time", "latitude", "longitude"), class_dts)

        # mask the dataset to the requested time
        mask = ds["solar_class"] == time
        ds_masked = ds_masked.where(mask)

        # set the local timezone
        ds_masked = ds_masked.assign_coords(valid_time=pd.to_datetime(ds["valid_time"].values).tz_localize("UTC").tz_convert(local_tz))

        # resample by local date
        logger.info("Resampling by local date...")
        ds_rs = ds_masked.resample(valid_time="1D").reduce(aggregation_func)

        # convert to tiff
        logger.info("Rasterizing resampled data...")
        n_bands = ds_rs.dims['valid_time']

        # polygon to raster cells for the first band
        logger.info("Converting polygons to raster cells...")
        raster = netcdf_to_tiff(ds_rs, band=1, variable=variable)
        res_poly2cell=polygon_to_raster_cells(
            vectors = healthsheds.geometry.values, # the geometries of the shapefile of the regions
            raster=raster.data, # the raster data above
            nodata=np.nan, # any intersections with no data, may have to be np.nan
            affine=raster.transform, # some math thing need to revise
            all_touched=True, 
            verbose=True
        )

        result_df = healthsheds[[hshd_unique_id, "geometry"]].copy()

        # loop over bands and aggregate to healthsheds
        for band in tqdm(range(1, n_bands + 1)):
            logger.info(f"Processing band {band} of {n_bands}...")
            
            day = band  # band is 1-indexed

            day_col = f"day_{day:02d}"

            raster = netcdf_to_tiff(ds_rs, band=band, variable=variable)
            result = aggregate_to_healthsheds(
                res_poly2cell=res_poly2cell,
                raster=raster,
                shapes=healthsheds,
                names_column=hshd_unique_id,
                aggregation_func=aggregation_func,
                aggregation_name=variable
            )
            
            result_df[day_col] = result[variable]

        # save to parquet
        result_df.to_parquet(f"{BLD}/{output_file}")

        logger.info("Aggregation complete.")
        
        return Path(f"{BLD}/{output_file}")
