# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/10_pytask_demo.qmd.

# %% auto 0
__all__ = ['task_create_random_data', 'task_plot_data', 'task_add_one', 'task_add_another_column']

# %% ../../notes/10_pytask_demo.qmd 3
import os
from pathlib import Path
from typing import Annotated

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from .config import BLD
from .config import data_catalog, demo_catalog

from pytask import PickleNode
from pytask import Product

# %% ../../notes/10_pytask_demo.qmd 5
def task_create_random_data(
        seed: Annotated[int, 42], # Default seed for reproducibility
        path_to_data: Annotated[Path, Product] = BLD / "data.pkl" # Path to the object in the build directory
    ) -> None:
    "Create a random data set and save it as a pickle file. Return the path to the saved file."
    rng = np.random.default_rng(seed)
    beta = 2

    x = rng.normal(loc=5, scale=10, size=1_000)
    epsilon = rng.standard_normal(1_000)

    y = beta * x + epsilon

    df = pd.DataFrame({"x": x, "y": y})

    # this is a tracked output, so we annotate the return value with `Annotated[Path, Product]`
    df.to_pickle(path_to_data)

# %% ../../notes/10_pytask_demo.qmd 11
def task_plot_data(
    path_to_data: Annotated[Path, BLD / "data.pkl"], # Path to the data file created by the previous task
    path_to_plot: Annotated[Path, Product] = BLD / "plot.png"  # Path to the build directory for the plot
) -> None:
    """
    Plot the data from the pickle file and save the plot. Note that this task:
        1. depends on the data.pkl file created by the previous task,
        2. does not return any value, but saves a plot to the build directory. So the side effect of the task is what we are interested in here (though this is probably bad practice).
    """

    df = pd.read_pickle(path_to_data)
    
    _, ax = plt.subplots()
    df.plot(x="x", y="y", ax=ax, kind="scatter")

    plt.savefig(path_to_plot)
    plt.close()

# %% ../../notes/10_pytask_demo.qmd 15
def task_add_one(
    path_to_data: Annotated[Path, BLD / "data.pkl"],  # Path to the data file created by the previous task
    node: Annotated[PickleNode, Product] = demo_catalog["mydata"]
) -> None:
    """
    Add one to the 'y' column of the data frame and save it as a new pickle file.
    """
    df = pd.read_pickle(path_to_data)
    df['z'] = df['y'] + 1
    
    node.save(df)

# %% ../../notes/10_pytask_demo.qmd 17
def task_add_another_column(
    df: Annotated[pd.DataFrame, demo_catalog["mydata"]] # which object in the catalog to fetch from the catalog with node.load()
) -> Annotated[pd.DataFrame, demo_catalog["mydata2"]]:  # which object in the catalog to save the return value to
    """
    Add another column to the data frame stored in the PickleNode.
    """

    # use the datacatalog directly to access the node
    # this is a bit like accessing the node in an iPython session, but pytask
    # will handle the serialization and deserialization for us
    df['w'] = df['z'] * df['y']
    
    return df
