# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notes/22_pytask_aggregate.qmd.

# %% auto 0
__all__ = ['compute_diurnal_class', 'resample_netcdf_diurnal']

# %% ../../notes/22_pytask_aggregate.qmd 3
from .config import BLD, data_catalog
from .core import ClimateDataFileHandler
from pyprojroot import here
import xarray as xr

# %% ../../notes/22_pytask_aggregate.qmd 7
from astral import Observer, sun
import pandas as pd
import numpy as np

# %% ../../notes/22_pytask_aggregate.qmd 13
from tqdm import tqdm

def compute_diurnal_class(
        ds: xr.Dataset
    )-> list:
    """
    Compute the diurnal value for each data point in the dataset.
    This function iterates over each data point in the dataset,
    calculates the sunrise and sunset times for the given time, latitude and longitude,
    and returns whether or not that data point is daytime or nighttime.
    """
    diurnal_class = []
    
    for i in tqdm(range(len(ds['valid_time'])), desc="Computing diurnal class"):
        time = ds['valid_time'].values[i]
        dt = pd.to_datetime(time, utc=True)
        observer = Observer(latitude=lat, longitude=long, elevation=0)
        sun_info = sun.sun(observer, date=dt)

        if dt < sun_info['sunrise']:
            diurnal_class.append("night")
        elif dt >= sun_info['sunrise'] and dt < sun_info['sunset']:
            diurnal_class.append("day")
        else:
            diurnal_class.append("night")
    
    return diurnal_class

# %% ../../notes/22_pytask_aggregate.qmd 24
import numpy as np

def resample_netcdf_diurnal(
        fpath: str, # Path to the netCDF file.
        diurnal_col: str = "diurnal_class", # Name of the column for diurnal classification.
        agg_func: callable = np.mean, # Aggregation function (e.g., np.mean, np.sum).
        time_dim: str = "valid_time", # Name of the time dimension in the dataset.
        chunks: dict | None = None # keywords for python's xarray module, e.g chunking
    ) -> xr.Dataset:   
    """
    Resample a netCDF file to a specified frequency and aggregation method.
    
    Args:
        fpath (str): Path to the netCDF file.
        diurnal_col (str): Name of the column for diurnal classification.
        agg_func (callable): Aggregation function (e.g., np.mean, np.sum).
    
    Returns:
        xarray.Dataset: Resampled dataset.
    """
    if chunks is None:
        with ClimateDataFileHandler(fpath) as handler:
            fpath = handler.get_dataset("instant")
            ds = xr.open_dataset(fpath)
    else:
        with ClimateDataFileHandler(fpath) as handler:
            fpath = handler.get_dataset("instant")
            ds = xr.open_dataset(fpath, chunks=chunks)

    diurnal_vals = compute_diurnal_class(ds)
    ds = ds.assign_coords(**{diurnal_col: ("valid_time", diurnal_vals)})

    if callable(agg_func):
        # Use xarray's reduce method with the callable
        ds.coords["date"] = ds[time_dim].dt.floor("D")
        return ds.groupby(["date", diurnal_col]).reduce(agg_func, dim=time_dim)
    else:
        raise TypeError("agg_func must be a callable function like np.mean, np.max, etc.")
