---
skip_showdoc: true
---

# Introduction to the ERA 5 Data

The ERA5 dataset is the fifth iteration of the ECMWF ReAnalysis dataset, spanning from 1950 to the present. ECMWF is the "European Centre for Medium-Range Weather Forecasts".
The dataset provides comprehensive and high-resolution historical weather and climate data. The source data is from the [Copernicus Climate Data Store (CDS)](https://cds.climate.copernicus.eu/#!/home). A comprehensive data documentation guide is available [here](https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation). In total, the entire CDS ERA data is over 10Petabytes.

Fortunately for us, there are existing [Python](https://github.com/Climate-CAFE/era5-daily-heat-aggregation-python) and [R](https://github.com/Climate-CAFE/era5-daily-heat-aggregation) packages that have gone ahead and demonstrated extracting the data from the API for us, so we are going to use those to develop our workflow. Specifically, we're trying to understand the
following characteristics of the data:

* size, 
* how to download, 
* what are the key transformations to map things into the health sheds
* two important variables: 
    * 2m air temp, and, 
    * 2m air dew point

Let's get started

Important: we need to install the CDS API first, so you'll need to grab an API key. First, you must register for an account and accept the T&Cs, afterwhich the page [here](https://ecmwf-projects.github.io/copernicus-training-c3s/cds-tutorial.html#install-the-cds-api-key) will autopopulate an API key for you. The following code shows a test case to make sure your API key works

```{python}
import cdsapi

client = cdsapi.Client()

dataset = 'reanalysis-era5-pressure-levels'
request = {
  'product_type': ['reanalysis'],
  'variable': ['geopotential'],
  'year': ['2024'],
  'month': ['03'],
  'day': ['01'],
  'time': ['13:00'],
  'pressure_level': ['1000'],
  'data_format': 'grib',
}
target = 'download.grib'

client.retrieve(dataset, request, target)
```

This demonstration is expected to amass 9GB of data for raw raster files (24 years, 12 files per year). The demonstration generates the 24 years of heat measures across Kenya administrative boundaries, in 1-month periods of ERA5-Land data across Kenya with three variables (2-m temp, dew point temp, skin temp)

```{python}
# imports as recommended by the github repo
import cdsapi
import geopandas as gpd
import os
```

I'll use pyprojroot to specify a data path

```{python}
from pyprojroot.here import here

ecmw_dir = here("data")
```

```{python}
def create_dir(path):

    if not os.path.exists(path):
        os.makedirs(path)

    return path
```

```{python}
create_dir(ecmw_dir)
```

```{python}
# create a directory for the kenya data
create_dir(os.path.join(ecmw_dir, "Kenya_GADM"))
```

Next, we need to manually fetch this GADM file for Kenya from here: https://gadm.org/download_country.html

This is a boundaries geopackage; GeoBoundaries is a global database of administrative boundaries (e.g., countries, states, provinces, districts). Hence, this file provides the
boundaries for Kenyan regions

```{python}
kenya_shape =  gpd.read_file(os.path.join(ecmw_dir, "Kenya_GADM/gadm41_KEN.gpkg"), layer = "ADM_ADM_0")
```

```{python}
kenya_shape
```

The bounding box represents the coordinates of the shapefile, which is what we'll
use to query Copernicus. Think of it like a mask provided in a file

```{python}
kenya_bbox = kenya_shape.total_bounds
```

```{python}
kenya_bbox
```

Technical: Add a small buffer around the bounding box to ensure the whole region 
is queried, and round the parameters to a 0.1 resolution. A 0.1 resolution
is applied because the resolution of netCDF ERA5 data is .25x.25
https://confluence.ecmwf.int/display/CKB/ERA5%3A+What+is+the+spatial+reference

```{python}
kenya_bbox[0] = round(kenya_bbox[0], 1) - 0.1
kenya_bbox[1] = round(kenya_bbox[1], 1) - 0.1
kenya_bbox[2] = round(kenya_bbox[2], 1) + 0.1
kenya_bbox[3] = round(kenya_bbox[3], 1) + 0.1
```

```{python}
# to build a query, specify [xmin, ymin, xmax, ymax]
query_area = [kenya_bbox[0], kenya_bbox[1], kenya_bbox[2], kenya_bbox[3]]
```

```{python}
query_years = list(range(2000, 2024))
query_years_str = [str(x) for x in query_years]

query_months = list(range(1, 13))
query_months_str = [str(x).zfill(2) for x in query_months]
```

```{python}
output_dir = create_dir(os.path.join(ecmw_dir, "ERA5_out"))
```

```{python}
for year_str in query_years_str:
    # Track progress
    print("Now processing year ", year_str, "\n")

    # For each year, the query is divided into each month sections. 
    # If a request is too large, it will not be accepted by the CDS servers, 
    # so this division of requests is required.

    for month_str in query_months_str:
        # Track progress
        print("Now processing month ", month_str, "\n")

        # The below is the formatted API request language. All of the inputs
        # specified below in proper formatting can be identified by forming a 
        # request using the Copernicus CDS point-and-click interface for data
        # requests. https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=form
        # Select the variables, timing, and netcdf as the output format, and then 
        # select "Show API Request" at the bottom of the screen. 
    
        # Note that the argument in the download() function is the file path and 
        # file name that data will be exported to and stored at. If using a loop, 
        # ensure that the unique features of each request are noted in the output.

        # Note: need to create "ERA5_Out" subfolder on your path
 
        dataset = "reanalysis-era5-land"
        request = {
                    "product_type": "reanalysis",
                    "variable": ["2m_dewpoint_temperature",
                                 "2m_temperature",
                                 "skin_temperature"], 
                    "year": year_str,
                    "month": month_str,
                    "day": [  
                            "01", "02", "03",
                            "04", "05", "06",
                            "07", "08", "09",
                            "10", "11", "12",
                            "13", "14", "15",
                            "16", "17", "18",
                            "19", "20", "21",
                            "22", "23", "24",
                            "25", "26", "27",
                            "28", "29", "30",
                            "31"],
                    "time": [
                             "00:00", "01:00", "02:00",
                             "03:00", "04:00", "05:00",
                             "06:00", "07:00", "08:00",
                             "09:00", "10:00", "11:00",
                             "12:00", "13:00", "14:00",
                             "15:00", "16:00", "17:00",
                             "18:00", "19:00", "20:00",
                             "21:00", "22:00", "23:00"],
                    "data_format": "netcdf",
                    "download_format": "unarchived",
                    "area": query_area
        }

        client = cdsapi.Client()
        client.retrieve(dataset, request).download(os.path.join(output_dir, 
                                                                "{}_{}.nc".format(year_str, month_str)))
```

From the logs, it looks like one month of data takes approximately 10 minutes. In this query, we might end up with 48 hours of downloading for the full 24 years. Clearly this will need to be multithreaded/paralleled to be efficient.

## Testing Soil Moisture Downloads

```{python}
import cdsapi

dataset = "reanalysis-era5-land"
request = {
    "variable": ["volumetric_soil_water_layer_1"],
    "year": "2009",
    "month": "01",
    "day": ["01"],
    "time": ["01:00"],
    "data_format": "netcdf",
    "download_format": "unarchived"
}

client = cdsapi.Client()
client.retrieve(dataset, request).download()
```

```{python}
from pyprojroot.here import here

ecmw_dir = here("notes/prototypes/")
```

```{python}
ecmw_dir / "soil.nc"
```

```{python}
import xarray
import os

temp_file = xarray.open_dataset(os.path.join(ecmw_dir / "soil.nc"), decode_coords="all")
```

```{python}
temp_file
```

```{python}
temp_file['swvl1'].plot()
```

```{python}

```